spring.application.name=property-api
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=hotel_ks
spring.cassandra.schema-action=recreate_drop_unused
spring.classformat.ignore=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration