services:
  cassandra:
    image: cassandra:latest
    container_name: hotel-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=hotel_cluster
      - CASSANDRA_DC=datacenter1
